name: a
title: a
description: a
type: a
value: a
require: true
format: a
pattern: a
minLength: 0
maxLength: 0
minimum: 0
exclusiveMinimum: 0
maximum: 0
exclusiveMaximum: 0
multipleOf: 0
additionalProperties: true
propertyNames: ["a"]
minProperties: 0
maxProperties: 0
patternProperties: a
contains: []
additionalItems: true
minItems: 0
maxItems: 0
render: a
condition: a
ignore: true
